- create:
    - ~/.config/starship
    - ~/.config/bash
    - ~/.config/shell
    - ~/.config/.bin

- link:
    ~/.bashrc: bash/bashrc
    ~/.config/starship/starship.toml: starship/starship.toml
    ~/.config/shell/aliases.sh: shell/aliases.sh
    ~/.bin/compress: shell/bin/compress
    ~/.bin/extract: shell/bin/extract
    ~/.bin/mcd: shell/bin/mcd
    ~/.bin/ssh-tmux: shell/bin/ssh-tmux
