- create:
    - ~/.gnupg
    - ~/.bin

- link:
    ~/.bin/pinentry-auto: gnupg/pinentry-auto
    ~/.gnupg/gpg.conf: gnupg/gpg.conf
    ~/.gnupg/gpg-agent.conf: gnupg/gpg-agent.conf
    ~/.gnupg/dirmngr.conf: gnupg/dirmngr.conf
