- create:
    - ~/.config/i3
    - ~/.config/i3blocks
    - ~/.config/i3blocks/blocks
    - ~/Pictures
    - ~/Pictures/Wallpapers

- link:
    ~/.xbindkeysrc: i3/xbindkeysrc
    ~/.config/i3/config: i3/config
    ~/.config/i3blocks/config_main: i3/blocks_main
    ~/.config/i3blocks/config_side: i3/blocks_side
    ~/.config/i3blocks/blocks/keyboard.sh: i3/blocks/keyboard.sh
    ~/.config/i3blocks/blocks/volume.sh: i3/blocks/volume.sh
    ~/.config/i3blocks/blocks/mediaplayer.sh: i3/blocks/mediaplayer.sh
    ~/Pictures/Wallpapers/4k_nord.png: i3/wallpapers/4k_nord.png
    ~/Pictures/Wallpapers/uw5k_nord.png: i3/wallpapers/uw5k_nord.png

- shell:
    - betterlockscreen --update ~/Pictures/Wallpapers/uw5k_nord.png
