- create:
    - ~/.config/starship
    - ~/.config/zsh

- link:
    ~/.zshrc: zsh/zshrc
    ~/.zshenv: zsh/zshenv
    ~/.config/starship/starship.toml: starship/starship.toml
    ~/.config/zsh/aliases.zsh: zsh/aliases.zsh
    ~/.config/zsh/bindings.zsh: zsh/bindings.zsh
    ~/.config/zsh/options.zsh: zsh/options.zsh
    ~/.config/zsh/completions.zsh: zsh/completions.zsh
    ~/.config/zsh/plugins.zsh: zsh/plugins.zsh
