[aws]
symbol = " "

[battery]
disabled = true

[conda]
disabled= true

[crystal]
disabled= true

[elixir]
disabled= true

[elm]
disabled= true

[erlang]
disabled= true

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
disabled = true

[nix_shell]
disabled = true

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
disabled = true

[python]
symbol = " "

[ruby]
disabled = true

[rust]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true
