#!/usr/bin/env sh

base=${BASE:-"${HOME}/.docker/definitions"}
version=${VERSION:-"3.8"}

compose() {
  stack=${1}

  if [ ! -f "${base}/${stack}.yml" ]; then
    echo "could not find '${stack}' stack"
    exit 1
  fi

  shift

  docker-compose -f "${base}/${stack}.yml" -p "${stack}" "${@}"
}

create_stack() {
  definition="${base}/${1}.yml"
  {
    echo "---"
    echo "version: \"${version}\""
    echo ""
    echo "services:"
  } > "$definition"
}

delete_stack() {
  rm -rf "${base}/${1}.yml"
}

stack=${1}

shift

case "${1}" in
  "--create") create_stack "${stack}"     ;;
  "--delete") delete_stack "${stack}"     ;;
  "")         compose "${stack}" config   ;;
  *)          compose "${stack}" "${@}" ;;
esac
