#!/usr/bin/env bash

base=${BASE:-"${HOME}/.docker/definitions"}
version=${VERSION:-"3.8"}

function compose() {
  if [[ ! -f "${base}/${1}.yml" ]]; then
    echo "could not find '${1}' stack"
    exit 1
  fi

  docker-compose -f "${base}/${1}.yml" -p "${1}" "${@:2}"
}

function create-stack() {
  definition="${base}/${1}.yml"
  {
    echo "---"
    echo "version: \"${version}\""
    echo ""
    echo "services:"
  } > "$definition"
}

function delete-stack() {
  rm -rf "${base}/${1}.yml"
}

case "${2}" in
  "--create") create-stack "${1}"     ;;
  "--delete") delete-stack "${1}"     ;;
  "")         compose "${1}" config   ;;
  *)          compose "${1}" "${@:2}" ;;
esac
