#!usr/bin/env zsh

# Execute code that does not affect the current session in the background.
{
  setopt LOCAL_OPTIONS EXTENDED_GLOB
  autoload -U zrecompile

  # Compile zcompdump, if modified, to increase startup speed.
  zcompdump="${HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zrecompile -pq "$zcompdump"
  fi

  # zcompile .zshrc
  zrecompile -pq "${HOME}/.zshrc"
  zrecompile -pq "${HOME}/.zprofile"
  zrecompile -pq "${HOME}/.zshenv"

  # recompile all zsh
  for f in "${HOME}/.config/zsh/*.zsh"; do
    zrecompile -pq $f
  done
} &!
