#!usr/bin/env zsh

################################################################################
# locale                                                                       #
################################################################################

if [[ -z "${LANG}" ]]; then
  export LANG="en_US.UTF-8"
  export LANGUAGE="en_US.UTF-8"
fi

export LC_TIME="de_DE.UTF-8"
export LC_MONETARY="de_DE.UTF-8"
export LC_PAPER="de_DE.UTF-8"
export LC_TELEPHONE="de_DE.UTF-8"
export LC_MEASUREMENT="de_DE.UTF-8"

export LESSCHARSET="utf-8"

# eliminates duplicates in *paths
typeset -gU cdpath fpath path
