#!/usr/bin/env zsh

# extend $PATH without duplicates
_extend_path() {
  if ! $( echo "$PATH" | tr ":" "\n" | grep -qx "$1" ) ; then
    export PATH="$1:$PATH"
  fi
}

################################################################################
# locale                                                                       #
################################################################################

export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_TIME="de_DE.UTF-8"
export LC_MONETARY="de_DE.UTF-8"
export LC_PAPER="de_DE.UTF-8"
export LC_TELEPHONE="de_DE.UTF-8"
export LC_MEASUREMENT="de_DE.UTF-8"

export LESSCHARSET="utf-8"

################################################################################
# paths                                                                        #
################################################################################

[[ -d "$HOME/.bin" ]] && _extend_path "$HOME/.bin"
[[ -d "$HOME/.local/bin" ]] && _extend_path "$HOME/.local/bin"
[[ -d "$HOME/.dotnet/tools" ]] && _extend_path "$HOME/.dotnet/tools"

################################################################################
# android                                                                      #
################################################################################

[[ -d "$HOME/.android/sdk" ]] && export ANDROID_HOME="$HOME/.android/sdk"; \
  _extend_path "$ANDROID_HOME/emulator"; \
  _extend_path "$ANDROID_HOME/tools"; \
  _extend_path "$ANDROID_HOME/tools/bin"; \
  _extend_path "$ANDROID_HOME/platform-tools"

################################################################################
# golang                                                                       #
################################################################################

[[ -d "$HOME/.go" ]] && \
  export GOPATH="$HOME/.go"; \
  export GOBIN="$GOPATH/bin"; \
  export CGO_ENABLED="0"; \
  export GO111MODULE="auto"; \
  _extend_path "$GOBIN"

################################################################################
# telemetry                                                                    #
################################################################################

export SAM_CLI_TELEMETRY="0"
export DOTNET_CLI_TELEMETRY_OPTOUT="1"

################################################################################
# history                                                                      #
################################################################################

export HISTFILE="$HOME/.zhistory"
export HISTSIZE="20000"
export SAVEHIST="$HISTSIZE"

################################################################################
# pager                                                                        #
################################################################################

export PAGER="/usr/bin/less"

################################################################################
# preferred text editor                                                        #
################################################################################

export EDITOR="/usr/bin/nvim"
export VISUAL="$EDITOR"

################################################################################
# colored man pages                                                            #
################################################################################

export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;38;5;74m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[38;33;246m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[04;38;5;146m'

################################################################################
# misc                                                                         #
################################################################################

# the time the shell waits, for another key to be pressed in milliseconds
export KEYTIMEOUT=1

# starship
[[ -f "$HOME/.config/starship/starship.toml" ]] && export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# terminal
export TERM="xterm-256color"

# electron
[[ -f "/usr/bin/trash" ]] && export ELECTRON_TRASH="/usr/bin/trash"

# wireshark ssl log
export SSLKEYLOGFILE="$HOME/.ssl-key.log"

# enable colored output from ls, etc. on FreeBSD-based systems
export CLICOLOR=1
