#!usr/bin/env zsh

if [ -t 0 ]; then
	export GPG_TTY=$TTY
	export PINENTRY_USER_DATA=USE_TTY=1
fi

################################################################################
# environment                                                                  #
################################################################################
[[ -f "/usr/bin/kitty" ]] && export TERMINAL="/usr/bin/kitty"

# load plugins
. $HOME/.config/zsh/plugins.zsh

# load configuration
. $HOME/.config/zsh/aliases.zsh
. $HOME/.config/zsh/bindings.zsh
. $HOME/.config/zsh/completions.zsh
. $HOME/.config/zsh/options.zsh

# load local configuration
if [[ -f $HOME/.config/zsh/local.zsh ]]; then
  . $HOME/.config/zsh/local.zsh
fi

if [[ -f /usr/share/doc/pkgfile/command-not-found.zsh ]]; then
  . /usr/share/doc/pkgfile/command-not-found.zsh
fi

eval "$(starship init zsh)"
