#!usr/bin/env bash

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -t 0 ]; then
	export GPG_TTY=$TTY
	export PINENTRY_USER_DATA=USE_TTY=1
fi

source $HOME/.config/shell/aliases.sh

# load local configuration
if [[ -f $HOME/.config/bash/local.sh ]]; then
  . $HOME/.config/bash/local.sh
fi

eval "$(starship init bash)"
